# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file


version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    reviewers:
      - "scality/object"
    commit-message:
      prefix: "gomod"
      include: "scope"
    labels:
      - "gomod"
      - "dependencies"
    ignore:
      - dependency-name: "github.com/aws/*"
        update-types:
          - "version-update:semver-minor"
    groups:
      go:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/aws/*"
      go-aws:
        patterns:
          - "github.com/aws/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "08:00"
    reviewers:
      - "scality/object"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "github-actions"
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"
