image:
  repository: ghcr.io/scality/cosi-driver
  tag: latest
  pullPolicy: IfNotPresent


replicaCount: 1

# Log levels define the verbosity of logs for various parts of the system.
# Use these levels to control the detail included in the logs:
# 1 - General configuration, routine logs
# 2 - Steady-state operations, HTTP requests, system state changes (default)
# 3 - Extended changes, additional system details
# 4 - Debug-level logs, tricky logic areas
# 5 - Trace-level logs, context for troubleshooting
logLevels:
  driver: "2"
  sidecar: "2"


namespace: scality-object-storage
fullnameOverride: scality-cosi-driver


serviceAccount:
  name: scality-object-storage-provisioner
  create: true

metrics:
  enabled: true
  port: 8080
  prefix: "scality_cosi_driver"
  address: "0.0.0.0:8080"
  path: "/metrics"

traces:
  # endpoint for trace collector to send traces to
  otel_endpoint: "http://localhost:4318"
  # prints traces to stdout if true and does not send to collector
  otel_stdout: false
  # Trace span service name
  otel_service_name: "cosi.scality.com"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"


env:
  POD_NAMESPACE:
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace


version: 0.1.0
