apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scality-cosi-driver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "scality-cosi-driver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scality-cosi-driver.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scality-cosi-driver.name" . }}
        app.kubernetes.io/part-of: container-object-storage-interface
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: scality-cosi-driver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--driver-prefix=cosi"
            - "--v={{ .Values.logLevels.driver }}"
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: objectstorage-provisioner-sidecar
          image: gcr.io/k8s-staging-sig-storage/objectstorage-sidecar:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--v={{ .Values.logLevels.sidecar }}"
          volumeMounts:
            - mountPath: /var/lib/cosi
              name: socket
      volumes:
        - name: socket
          emptyDir: {}
