apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scality-cosi-driver-provisioner-role
  annotations:
    description: Role for Scality COSI Driver Provisioner with permissions for managing COSI resources and related objects.
rules:
  - apiGroups: ["objectstorage.k8s.io"]
    resources:
      - buckets
      - bucketaccesses
      - bucketclaims
      - bucketaccessclasses
      - buckets/status
      - bucketaccesses/status
      - bucketclaims/status
      - bucketaccessclasses/status
    verbs:
      - create
      - get
      - update
      - delete
      - list
      - watch
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - create
      - get
      - update
      - delete
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
      - events
      - services
      - endpoints
    verbs:
      - create
      - get
      - update
      - delete
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scality-cosi-driver-provisioner-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: scality-cosi-driver-provisioner-role
  apiGroup: rbac.authorization.k8s.io
