apiVersion: v1
kind: Service
metadata:
  name: {{ include "scality-cosi-driver.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ include "scality-cosi-driver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: container-object-storage-interface
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "scality-cosi-driver.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}