apiVersion: objectstorage.k8s.io/v1alpha1
kind: Bucket
metadata:
  name: brownfield-bucket # should be same as bucket name
  namespace: container-object-storage-system
spec:
  bucketClaim: {}
  bucketClassName: brownfield-bucket-class
  driverName: cosi.scality.com
  deletionPolicy: Retain
  existingBucketID: brownfield-bucket # name of pre-existing bucket in S3
  parameters:
    objectStorageSecretName: s3-secret-for-cosi
    objectStorageSecretNamespace: default
  protocols:
    - S3
