kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: my-bucket-class # bucket prefix, followed by UUID for every bucket claim
driverName: cosi.scality.com
deletionPolicy: Retain
parameters:
  objectStorageSecretName: s3-secret-for-cosi
  objectStorageSecretNameSpace: default
