apiVersion: v1
kind: Secret
metadata:
  name: s3-secret-for-cosi
  namespace: default
type: Opaque
stringData:
  accessKeyId: PBUOB68AVF39EVVAFNFL  # Plain text access key, generated in the CI
  secretAccessKey: P+PK+uMB9spUc21huaQoOexqdJoV00tSnl+pc7t7  # Plain text secret key
  endpoint: http://localhost:8000  # Plain text endpoint
  region: us-west-1  # Plain text region
  iamEndpoint: http://localhost:8600 # [Optional] Plain text IAM endpoint, if different from the S3 endpoint
