apiVersion: v1
kind: Secret
metadata:
  name: s3-secret-for-cosi
  namespace: default
type: Opaque
stringData:
  COSI_S3_ACCESS_KEY_ID: accessKey1  # Plain text access key
  COSI_S3_SECRET_ACCESS_KEY: verySecretKey1  # Plain text secret key
  COSI_S3_ENDPOINT: http://localhost:8000  # Plain text endpoint
  COSI_S3_REGION: us-west-1  # Plain text region
