apiVersion: v1
kind: Secret
metadata:
  name: s3-secret-for-cosi
  namespace: default
type: Opaque
stringData:
  COSI_DRIVER_OSP_ACCESS_KEY_ID: PBUOB68AVF39EVVAFNFL  # Plain text access key, generated in the CI
  COSI_DRIVER_OSP_SECRET_ACCESS_KEY: P+PK+uMB9spUc21huaQoOexqdJoV00tSnl+pc7t7  # Plain text secret key
  COSI_DRIVER_OSP_ENDPOINT: http://localhost:8000  # Plain text endpoint
  COSI_DRIVER_OSP_REGION: us-west-1  # Plain text region
