apiVersion: v1
kind: Service
metadata:
  name: scality-cosi-metrics
  labels:
    app.kubernetes.io/name: scality-cosi-driver
    app.kubernetes.io/part-of: container-object-storage-interface
spec:
  selector:
    app.kubernetes.io/name: scality-cosi-driver
  ports:
    - protocol: TCP
      port: 8080  # The port Prometheus will scrape
      targetPort: 8080  # The port exposed by the container