apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scality-cosi-driver-provisioner-role
rules:
  - apiGroups: ["objectstorage.k8s.io"]
    resources: ["buckets", "bucketaccesses", "bucketclaims", "bucketaccessclasses", "buckets/status", "bucketaccesses/status", "bucketclaims/status", "bucketaccessclasses/status"]
    verbs: ["get", "list", "watch", "update", "create", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["get", "delete", "update", "create"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scality-cosi-driver-provisioner-role-binding
subjects:
  - kind: ServiceAccount
    name: scality-cosi-driver-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: scality-cosi-driver-provisioner-role
  apiGroup: rbac.authorization.k8s.io
