name: CI Build and Unit Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: unit-tests-with-ginkgo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      # Install Ginkgo CLI
      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: make test

      - name: Upload test coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: scality/cosi-driver

  dev-container-build:
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    with:
      context: .
      name: cosi-driver
      namespace: ${{ github.repository_owner }}
      tag: ${{ github.sha }}
